### ISSUE TITLE
Windows authentication

### ISSUE THREAD

**Issue by michelebruniCAI** [UiPath/uipathcli#119]
Is possible to use WinAuth in Uipath CLI?

I try with User and password and i get an error:

`Could not connect to Orchestrator: [...] , Tenant: [...], Username: [...], Password: ***, OrganizationUnit: [...], UseWindowsCredentials: False.`

I try to read docs and help but i didn't find reference about how to set option "UseWindowsCredentials" to true

**Comment by thschmitt** [comment]
The `uipathcli` only supports the following ways to authorize with the UiPath services:
- Client Credentials
- OAuth Login
- Personal Access Token

see https://github.com/UiPath/uipathcli#configuration

But from the message it looks like you might be using the CLI for executing certain pre-defined tasks for RPA package management and testing. You find more details [here](https://docs.uipath.com/automation-ops/automation-cloud/latest/user-guide/uipath-command-line-interface).
